Pin Ubuntu to 22.04 for Galaxy releases using Python 3.7
The ubuntu-latest runner label is moving to 24.04, see
https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

Fix the following error at the setup-python step:

```
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```