Require requests>=2.5.0
To fix the following traceback when using requests 2.4.3 under ipython:
```
In [1]: from bioblend import galaxy
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8a068c0a120f> in <module>()
----> 1 from bioblend import galaxy

/tmp/test_requests/lib/python2.7/site-packages/bioblend/galaxy/__init__.py in <module>()
      2 A base representation of an instance of Galaxy
      3 """
----> 4 from bioblend.galaxy import (config, datasets, datatypes, folders, forms,
      5                              ftpfiles, genomes, groups, histories, jobs,
      6                              libraries, quotas, roles, tool_data, tools,

/tmp/test_requests/lib/python2.7/site-packages/bioblend/galaxy/config/__init__.py in <module>()
      3
      4 """
----> 5 from bioblend.galaxy.client import Client
      6
      7

/tmp/test_requests/lib/python2.7/site-packages/bioblend/galaxy/client.py in <module>()
      8 import time
      9
---> 10 import requests
     11 from requests.packages.urllib3.exceptions import ProtocolError
     12

/tmp/test_requests/lib/python2.7/site-packages/requests/__init__.py in <module>()
     51 # Attempt to enable urllib3's SNI support, if possible
     52 try:
---> 53     from .packages.urllib3.contrib import pyopenssl
     54     pyopenssl.inject_into_urllib3()
     55 except ImportError:

/tmp/test_requests/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py in <module>()
     71 _openssl_versions = {
     72     ssl.PROTOCOL_SSLv23: OpenSSL.SSL.SSLv23_METHOD,
---> 73     ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
     74     ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
     75 }

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```