Increase requests min version because of Ubuntu bug.
In Ubuntu 14.04.2 (trusty)

import bioblend.galaxy

tracebacks with:

  File "<stdin>", line 1, in <module>
  File "bioblend/galaxy/__init__.py", line 11, in <module>
    from bioblend.galaxyclient import GalaxyClient
  File "bioblend/galaxyclient.py", line 12, in <module>
    from requests_toolbelt import MultipartEncoder
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/__init__.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/__init__.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/adapters/ssl.py", line 13, in <module>
    SSLError -- exception raised for I/O errors
ImportError: No module named packages.urllib3.poolmanager

because in python-requests-2.2.1-1ubuntu0.2 and python-requests-2.3.0-1
requests is patched to not ship their own version of urllib3:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753578

This has been fixed in python-requests-2.4.3-1 .