Fix ``TestGalaxyHistories::test_import_history()`` test on Galaxy 22.05
Fix `bioblend.ConnectionError: Unexpected HTTP status code: 500: Internal Server Error`
error caused by the following traceback on upcoming Galaxy 22.05
which uses FastAPI:

```
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/webapps/galaxy/fast_app.py", line 103, in add_x_frame_options
    response = await call_next(request)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 217, in app
    solved_result = await solve_dependencies(
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/.venv/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 527, in solve_dependencies
    solved = await call(**sub_values)
  File "/usr/users/ga002/soranzon/software/nsoranzo_galaxy/lib/galaxy/webapps/galaxy/api/__init__.py", line 332, in _as_form
    return cls(**data)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CreateHistoryFormData
archive_type
  value is not a valid enumeration member; permitted: 'url', 'file' (type=type_error.enum; enum_values=[<HistoryImportArchiveSourceType.url: 'url'>, <HistoryImportArchiveSourceType.file: 'file'>])
```